In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Ai/House Price India.csv')
df.head()

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]

In [ ]:
df.shape

(14620, 23)

In [ ]:
df.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     14620 non-null  int64  
 1   Date                                   14620 non-null  int64  
 2   number of bedrooms                     14620 non-null  int64  
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64  
 5   lot area                               14620 non-null  int64  
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64  
 8   number of views                        14620 non-null  int64  
 9   condition of the house                 14620 non-null  int64  
 10  grade of the house                     14620 non-null  int64  
 11  Ar

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
     

In [ ]:
df.head()
     

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]

In [ ]:
x = df.iloc[:,0:-1].values
y= df.iloc[:,4:5].values
     

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.3,random_state = 0)
     

In [ ]:
xtrain.shape

(10234, 22)

In [ ]:
xtest.shape

(4386, 22)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
     

In [ ]:
# create ANN structure

regressor = Sequential()
regressor.add(Dense(4,activation = 'relu'))
regressor.add(Dense(12,activation = 'relu'))
regressor.add(Dense(9,activation = 'relu'))
regressor.add(Dense(1,activation = 'linear'))
     

In [ ]:
# compiling the ANN model
 
regressor.compile(optimizer = 'adam',loss= 'mse',metrics = ['mse'])
     

In [ ]:
# Training the model
regressor.fit(xtrain,ytrain,batch_size = 10,epochs = 300)


Epoch 1/300
1024/1024 [==============================] - 3s 2ms/step - loss: 1124547952640.0000 - mse: 1124547952640.0000
Epoch 2/300
1024/1024 [==============================] - 3s 2ms/step - loss: 1118034.7500 - mse: 1118034.7500
Epoch 3/300
1024/1024 [==============================] - 2s 2ms/step - loss: 1346738.8750 - mse: 1346738.8750
Epoch 4/300
1024/1024 [==============================] - 2s 2ms/step - loss: 1881524.2500 - mse: 1881524.2500
Epoch 5/300
1024/1024 [==============================] - 2s 2ms/step - loss: 3956182.5000 - mse: 3956182.5000
Epoch 6/300
1024/1024 [==============================] - 2s 2ms/step - loss: 2631290624.0000 - mse: 2631290624.0000
Epoch 7/300
1024/1024 [==============================] - 2s 2ms/step - loss: 3376472576.0000 - mse: 3376472576.0000
Epoch 8/300
1024/1024 [==============================] - 2s 2ms/step - loss: 2301108224.0000 - mse: 2301108224.0000
Epoch 9/300
1024/1024 [==============================] - 2s 2ms/step - loss: 1219375872.00

In [ ]:
ytest
     

array([[1440],
       [4270],
       [1010],
       ...,
       [2190],
       [1510],
       [1340]])

In [ ]:
y_pred = regressor.predict(xtest)
y_pred
     

138/138 [==============================] - 0s 1ms/step


array([[2105.584],
       [2105.584],
       [2105.584],
       ...,
       [2105.584],
       [2105.584],
       [2105.584]], dtype=float32)

In [ ]:
# evaluation

from sklearn.metrics import r2_score

r2_score(ytest,y_pred)*100

-0.03743330183976212

In [ ]:
86.50941817205249


86.50941817205249

In [ ]:
y_pred.flatten()
     
     

array([2105.584, 2105.584, 2105.584, ..., 2105.584, 2105.584, 2105.584],
      dtype=float32)

In [ ]:
pd.DataFrame({'Actual value':ytest.flatten(),'Predicted value':y_pred.flatten()}).head(10)
     

Actual value  Predicted value
0          1440      2105.583984
1          4270      2105.583984
2          1010      2105.583984
3          1970      2105.583984
4          2320      2105.583984
5          1390      2105.583984
6          4070      2105.583984
7          2050      2105.583984
8          6880      2105.583984
9          2690      2105.583984

In [ ]:
df.head()

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]